
const StoreData=[
    {Name:'john',
    Age:26,
    Course:'MERN',
    Batch:'October',
    },
    {Name:'Doe',
    Age:25,
    Course:'MERN',
    Batch:'November',
    },
    {Name:'Biden',
    Age:26,
    Course:'MERN',
    Batch:'September',
    },
    {Name:'Barar',
    Age:22,
    Course:'MERN',
    Batch:'September',
    },
    {Name:'Christ',
    Age:23,
    Course:'MERN',
    Batch:'October',
    },
    {Name:'Elent',
    Age:23,
    Course:'MERN',
    Batch:'November',
    },
]
export default StoreData;